apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-ads
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ms-ads
  template:
    metadata:
      labels:
        app: ms-ads
    spec:
      containers:
        - image: rsobook/ms-ads:2.0.4
          name: ms-ads
          env:
            - name: PORT
              value: '80'
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://ms-etcd:2379
          ports:
          - containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10